### ISSUE TITLE
Uncaught Error: Encountered a GraphQL validation error processing file 

### ISSUE THREAD

**Issue by transedward** [facebook/relay#105]
I'm currently working on an example from flux-chat to relay
https://github.com/transedward/relay/tree/master/examples/chat
I face a problem on console and it said check your terminal
But my terminal is fine and didn't show anything, how can I further useful information

**Comment by yungsters** [comment]
> I face a problem on console [...]

Can you copy/paste the problem you're running into here?

**Comment by josephsavona** [comment]
It sounds like the default dev server configuration isn't outputting GraphQL validation errors correctly on the console. Thanks for bringing this up, I can look into it.

**Comment by josephsavona** [comment]
This should be resolved by #96 - thanks @devknoll!

**Comment by alexandrethsilva** [comment]
@transedward, This issue still happens to me. Was it solved for you? Because if it was I'll probably have to try and check if it's something else on my end.

**Comment by transedward** [comment]
@alexandrethsilva Hey, I don't remember really well, but check your babel-relay-plugin for sure. and Maybe open another issue if there is any useful error or warning message. I haven't encounter that problem since then.
