### ISSUE TITLE
RANGE_DELETE and RANGE_ADD on connections with arguments

### ISSUE THREAD

**Issue by yachaka** [facebook/relay#1462]
I'm trying to achieve a mutation which is a RANGE_DELETE + a RANGE_ADD on a connection, but only on the specified arguments.

Scenario : the logged user, `Viewer` can see requests from others users and approve them.

The `User` type has a field `viewableRequests`, which is a relay connection, and with an extra optional argument `state`, which will filter the requests and only keep the one with the corresponding state.

Schema :
```js
type User {
  id: ID
  viewableRequests(first: Int, [...], state: RequestStateEnum): ViewableRequestsConnection
}

type ViewableRequestsConnection {
  edges: [RequestEdge]
  ...
}

type RequestEdge {
  cursor: GraphQLString
  node: Request
}

type Request {
  id: ID
  user_id: Int
  state: RequestStateEnum
}

enum RequestStateEnum {
  pending
  approved
}
```
So if I call `viewableRequests(state: pending)`, I only get requests with the pending state, and if I call `viewableRequests(state: approved)`, I only get the the requests with the approved state.

How can I write a `ApproveRequest` mutation that will do a RANGE_DELETE on the `viewableRequests(state: pending)` connection, and a RANGE_ADD on the `viewableRequests(state: approved)` connection, and how should I shape the `getOptimisticResponse()` method ?

Here is my mutation schema :
```
type ApproveRequestInput {
  requestId: ID
}

type ApproveRequestPayload {
  viewer: User
  approvedRequest: Request
}

mutation {
  approveRequest($input: ApproveRequestInput): ApproveRequestPayload
}
```
  
Here is my current code :
```js
import Relay, {
  Mutation,
} from 'react-relay';

export default class ApproveRequestMutation extends Mutation {
  static fragments = {
    viewer: () => Relay.QL`
      fragment on User {
        id
      }
    `,
    request: () => Relay.QL`
      fragment on Request {
        id
      }
    `,
  };

  getMutation() {
    return Relay.QL`mutation { approveRequest }`;
  }

  getVariables() {
    return {
      requestId: this.props.request.id,
    };
  }

  getFatQuery() {
    return Relay.QL`
      fragment on ApproveRequestPayload @relay(pattern: true) {
        viewer {
          pendingRequests: viewableRequests(state: pending)
          approvedRequests: viewableRequests(state: approved)
        }
        approvedRequest
      }
    `;
  }

  getOptimisticResponse() {
    return {
      // What should I write here ?
    };
  }

  getConfigs() {
    // The RANGE_DELETE config is not working ; how can I make it work ?
    return [{
      type: 'RANGE_DELETE',
      parentName: 'viewer',
      parentID: this.props.viewer.id,
      connectionName: 'pendingRequests',
      deletedIDFieldName: ['approvedRequest'],
      pathToConnection: ['viewer', 'pendingRequests'],
    }];
    // How can I can add here a RANGE_ADD config for the `approvedRequests` connection ?
    // I guess I must add an `approvedRequestEdge` on the mutation payload, but what is the config then ?
  }

}
```

I've posted this also on StackOverflow : 
http://stackoverflow.com/questions/40914883/range-delete-and-range-add-on-connections-with-arguments

**Comment by JCMais** [comment]
Is this issue resolved with Relay Modern?

**Comment by yachaka** [comment]
@JCMais Relay Modern exposes an other API, that might feel like a better way (I do), but it doesn't resolve this issue with the first Relay

**Comment by sibelius** [comment]
@yachaka you can use the low level mutation api from relay classic `Relay.GraphQLMutation` to solve this

**Comment by wincent** [comment]
The old mutations API is no longer being actively worked on or supported, and Relay Modern is now out, so I'm going to close this one in order to keep the issue tracker focused on the stuff that is currently being worked on. If you have a specific question with how to approach mutations within the context of Relay Modern, let's start a new issue for that. Thanks!
