### ISSUE TITLE
[Modern] Paging fetches data but props are not updates

### ISSUE THREAD

**Issue by luongthanhlam** [facebook/relay#2195]
I cloned and run this repo https://github.com/AndreiCalazans/hackernews-react-relay because of a problem in another project I have that also involves a PaginationContainer nested inside a QueryRenderer. The problem is that relay.loadMore(4) leads to the correct data being fetched from the server, but the props of the pagination component never get updated. This repo currently has the same wrong behavior.

In the picture you can see the 2nd correct fetch and the old items on the pagination

![image](https://user-images.githubusercontent.com/7001025/32245980-3b0afc12-be86-11e7-8e91-63061d66a4a2.png)

Anybody got any Idea?

**Comment by AndreiCalazans** [comment]
Hello @luongthanhlam I just pushed a fix to that repo.

The problem was that We weren't setting the arguments for filter, therefore on the refetch it was calling it as null which broke the refetch.

<img width="276" alt="screen shot 2017-11-16 at 08 34 11" src="https://user-images.githubusercontent.com/20777666/32887117-e97bfe98-caa9-11e7-98f0-fe52ab3ba7c9.png">

here is the fix https://github.com/AndreiCalazans/hackernews-react-relay/blob/f4893c6faa7065e4a1b2be2aa4bdb5199d758e0a/src/components/LinkList.js#L159

**Comment by sibelius** [comment]
another solution would be use use filters: [] on @connection directive

https://github.com/AndreiCalazans/hackernews-react-relay/blob/f4893c6faa7065e4a1b2be2aa4bdb5199d758e0a/src/components/LinkList.js#L116

`@connection(key: "LinkList_allLinks", filters: [])`

**Comment by luongthanhlam** [comment]
@AndreiCalazans: that fixed it. thanks!
@sibelius : I tried but it's still not work
