### ISSUE TITLE
@catch doesn't work on fragment root of useRefetchableFragment nor usePaginationFragment

### ISSUE THREAD

**Issue by christiansany** [facebook/relay#5070]
Hey

Unfortunately there are issues with `@catch` in combination with `useRefetchableFragment` and `usePaginationFragment`.
On a surface level, there is no issue, until `refetch` or `loadNext` is called. When these functions are called, everything goes boom.

Given a component like this here, `refetch` only works when the `id` is manually provided. And the `loadNext` function doesn't work at all.

```tsx
import { graphql, usePaginationFragment } from "@segments/relay";
import { type FunctionComponent, startTransition } from "react";
import type { brandForumContextCommunityDiscussionsList$key } from "./__generated__/brandForumContextCommunityDiscussionsList.graphql.ts";
import type {
  brandForumContextCommunityDiscussionsListRefetchQuery,
  ProductListSortOrder,
} from "./__generated__/brandForumContextCommunityDiscussionsListRefetchQuery.graphql.ts";
interface IBrandForumContextCommunityDiscussionsListProps {
  brandKey: brandForumContextCommunityDiscussionsList$key;
}

export const BrandForumContextCommunityDiscussionsList: FunctionComponent<
  IBrandForumContextCommunityDiscussionsListProps
> = ({ brandKey }) => {
  const {
    data: brand,
    loadNext,
    refetch,
  } = usePaginationFragment<
    brandForumContextCommunityDiscussionsListRefetchQuery,
    brandForumContextCommunityDiscussionsList$key
  >(
    graphql`
      fragment brandForumContextCommunityDiscussionsList on Brand
      @argumentDefinitions(
        first: { type: "Int", defaultValue: 5 }
        after: { type: "String" }
        order: { type: "ProductListSortOrder", defaultValue: AVAILABILITY }
      )
      @refetchable(
        queryName: "brandForumContextCommunityDiscussionsListRefetchQuery"
      )
      @catch {
        products(first: $first, after: $after, order: $order)
          @connection(key: "brandForumContextCommunityDiscussionsList_products")
          @required(action: THROW) {
          edges @required(action: THROW) {
            node {
              id
              name
            }
          }
        }
      }
    `,
    brandKey,
  );

  if (!brand.ok) {
    throw new Error("Simple here to demo purpose");
  }

  const onOrderToggle = (order: ProductListSortOrder) => {
    startTransition(() => {
      refetch({
        // 👇 When the id is not manually provided, this will result in a runtime error
        id: brand.value.id,
        order,
      });
    });
  };

  return (
    <>
      <button onClick={() => onOrderToggle("HIGHEST_PRICE")}>
        Change sort
      </button>
      <ul>
        {brand.value.products.edges.map((edge) => (
          <li key={edge.node.id}>{edge.node.name}</li>
        ))}
      </ul>
      {/* 👇 When loadNext is called, this will execute the refetch query with id: null */}
      <button onClick={() => loadNext(2)}>Load more</button>
    </>
  );
};

```

The expectation for this would be that it just works as expected or that the relay compiler tells us that using @catch is not allowed here.

**Comment by tyao1** [comment]
The issue may have been fixed in https://github.com/facebook/relay/commit/55dff358f4271f6f5aee1c59e3afcc45ac258879

**Comment by christiansany** [comment]
I've checked with the version https://www.npmjs.com/package/react-relay/v/0.0.0-main-a0680e86 yesterday and the issue still persists. But maybe that's the wrong version still.
Additionally, the issue seems to address when `@catch(to: NULL)` is placed on the same field the `@connection` directive is placed on. The issue reported here is about adding `@catch` to the root of the fragment.

**Comment by christiansany** [comment]
Can we have an update here?
This is (at least from our perspective) a problem that should be addressed quickly, as there is no indicator that this would not work, but it doesn't.

**Comment by captbaritone** [comment]
Hey. Thanks for the report and sorry for the delay I've been out for GraphQL conf and then some PTO. Would you mind opening a PR with a repro test case we can use? You should be able to copy/paste/adapt the test here: https://github.com/facebook/relay/blob/3cfded6512cf868667118f6b76fe895a85dbc5cf/packages/react-relay/relay-hooks/__tests__/usePaginationFragmentCatch-test.js#L4

**Comment by christiansany** [comment]
Hey, yes I can, will be next week though

**Comment by christiansany** [comment]
Hey @captbaritone, one week, or 6 months ... 😅😅😅
But here it is: https://github.com/facebook/relay/pull/5281
The PR adds a new test for usePaginationFragment, where the `@catch` is on the fragment root, and this messes with different things. The test tests for the returned `hasNext` value.

I've also created a reproduction of this Bug in https://github.com/christiansany/relay-playground/pull/2/changes#diff-e5883dc570e2171e8e8a19e39bacf10cd555df33e0d4c5f41910bb2670a0c4d2. My test project uses TypeScript, and not flow.

The Expectation would be that this either works as expected (`hasNext` & `loadNext` work correctly), or that the relay-compiler actively prevents this.

I'd be happy to try ans solve the issue/bug, but I need guidance if this is something that should be prevented on compiler level, or if `usePaginationFragment` should support this case.

**Comment by christiansany** [comment]
I've updated the PR https://github.com/facebook/relay/pull/5281 to also include the fix for it :)
